" Configuration file for vim
set ai                  " auto indenting
set history=100         " keep 100 lines of history
set ruler               " show the cursor position
syntax on               " syntax highlighting
set hlsearch            " highlight the last searched term
set background=dark

set modelines=0		" CVE-2007-2438

" Normally we use vim-extensions. If you want true vi-compatibility
" remove change the following statements
set nocompatible	" Use Vim defaults instead of 100% vi compatibility

" Whitespace
set nowrap
"set columns=80
"Python 
set tabstop=4
set shiftwidth=4 
set softtabstop=4
set expandtab		 	" use spaces not tabs

set backspace=indent,eol,start	" more powerful backspacing

" Searching
set hlsearch
set incsearch
set ignorecase
set smartcase

set encoding=utf-8
set showcmd
" Don't write backup file if vim is being called by "crontab -e"
au BufWrite /private/tmp/crontab.* set nowritebackup
" Don't write backup file if vim is being called by "chpass"
au BufWrite /private/etc/pw.* set nowritebackup

set viminfo=

" shortcuts
map N :tabnext<CR>
map P :tabprevious<CR>

" Related to  python mode
set showmatch
set ignorecase
set showmode
"set ts=4
"set sw=4
set autoindent
set smartindent
set number
imap <c-space> <c-x><c-o>

filetype plugin indent on
filetype on
filetype plugin on

if exists('+colorcolumn')
    set colorcolumn=80
else
    au BufWinEnter * let w:m2=matchadd('ErrorMsg', '\%>80v.\+', -1)
endif

nmap j gj
nmap k gk

cnoremap <C-a>  <Home>
cnoremap <C-b>  <Left>
cnoremap <C-f>  <Right>
cnoremap <C-d>  <Delete>
cnoremap <M-b>  <S-Left>
cnoremap <M-f>  <S-Right>
cnoremap <M-d>  <S-right><Delete>
cnoremap <Esc>b <S-Left>
cnoremap <Esc>f <S-Right>
cnoremap <Esc>d <S-right><Delete>
cnoremap <C-g>  <C-c>

nmap <C-e> :e#<CR>
nmap <C-n> :bnext<CR>
nmap <C-p> :bprev<CR>


nmap ; :CtrlPBuffer<CR>

execute pathogen#infect()

"Automatically remove whitespace
autocmd BufWritePre *.py :%s/\s\+$//e
autocmd BufWritePost *.py call Flake8()
au BufNewFile,BufRead *.py
    \ set tabstop=4 |
    \ set softtabstop=4 |
    \ set shiftwidth=4 |
    \ set textwidth=79 |
    \ set expandtab |
    \ set autoindent |
    \ set fileformat=unix |

au BufNewFile,BufRead *.js,*.html,*.css
    \ set tabstop=2 |
    \ set softtabstop=2 |
    \ set shiftwidth=2 |
" Auto start nerdtree and nerdtreemirror
" autocmd VimEnter * NERDTree
" autocmd VimEnter * wincmd p
" let g:NERDTreeWinPos = "right"
" autocmd VimEnter * nmap <F3> :NERDTreeToggle<CR>
" autocmd VimEnter * imap <F3> <Esc>:NERDTreeToggle<CR>a
" let NERDTreeWinSize=35
" python from powerline.vim import setup as powerline_setup
" python powerline_setup()
" python del powerline_setup
set laststatus=2
set t_Co=256
